[package]
name = "vrc-ban"
version = "0.3.10"
authors = ["Shayne Hartford <shaybox@shaybox.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "vrc-ban-api"
path = "src/bin/api.rs"

[[bin]]
name = "vrc-ban-bot"
path = "src/bin/bot.rs"

[dependencies]
cached = { version = "0.53", features = ["async"] }
chrono = { version = "0.4", features = ["serde"] }
color-eyre = { version = "0.6", features = ["issue-url"] }
derive-config = { version = "2", features = ["json", "toml"] }
indexmap = { version = "2", features = ["rayon"] }
maud = { version = "0.26", features = ["rocket"] }
poise = { version = "0.6", features = ["collector"] }
regex = { version = "1", features = ["logging"] }
reqwest = { version = "0.12", features = ["json"], default-features = false }
rocket = { version = "0.5", features = ["json"] }
serde = { version = "1", features = ["derive"] }
totp = { version = "5", package = "totp-rs" }
vrc = { git = "https://github.com/SheaFoxx/vrc_rs.git", features = ["api_client"] }
# vrc = { path = "vrc_rs", features = ["api_client"] }

[features]
default = ["rustls-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

[lints.clippy]
pedantic = "warn"
nursery = "warn"
